SELECT *
FROM V$SQLAREA area
WHERE area.PARSING_SCHEMA_NAME = 'HSSAMPAIO';

SELECT *
FROM ALL_TAB_COLUMNS atc
WHERE atc.COLUMN_NAME LIKE '%DESTINO%'
AND atc.OWNER = 'DBAMV'
ORDER BY 1 ASC;

SELECT *
FROM ALL_TAB_COLUMNS atc
WHERE atc.COLUMN_NAME LIKE '%DT_ENTRADA%'
AND atc.TABLE_NAME IN (SELECT TABLE_NAME FROM ALL_TAB_COLUMNS WHERE COLUMN_NAME LIKE '%ATENDIME%')
AND atc.OWNER = 'DBAMV'
ORDER BY 1 ASC

SELECT * FROM DBAMV.VDIC_RASTREAMENTO_PONTUARIO;

SELECT * FROM dbamv.REG_FAT ORDER BY 1 DESC;
SELECT * FROM Dbamv.PROTOCOLOS ORDER BY 1 DESC;
SELECT * FROM Dbamv.IT_SAME_PROTOCOLOS ORDER BY 1 DESC;
SELECT * FROM DBAMV.SAME ORDER BY DT_CADASTRO DESC;
SELECT * FROM dbamv.IT_SAME ORDER BY 1 DESC;
SELECT * FROM DBAMV.REG_FAT ORDER BY 1 DESC;
SELECT * FROM dbamv.ITREG_FAT ORDER BY 1 DESC;

SELECT * FROM dbamv.ATENDIME atd WHERE atd.CD_PACIENTE = 740618; --ATD 5046866

SELECT * FROM DBAMV.VDIC_RASTREAMENTO_PONTUARIO WHERE COD_ATENDIMENTO = 5046866;

SELECT pro.*
FROM dbamv.PROTOCOLOS pro
INNER JOIN dbamv.IT_SAME_PROTOCOLOS ipro
  ON ipro.CD_PROTOCOLO = pro.CD_PROTOCOLO
WHERE ipro.CD_ATENDIMENTO = 5040360
AND ipro.CD_PROTOCOLO = (SELECT CD_ATENDIMENTO, MAX(CD_PROTOCOLO) 
                         FROM dbamv.IT_SAME_PROTOCOLOS 
                         WHERE CD_ATENDIMENTO = ipro.CD_ATENDIMENTO
                         GROUP BY CD_ATENDIMENTO)


 
