SELECT itsp.* 
FROM dbamv.IT_SAME_PROTOCOLOS itsp 
WHERE itsp.CD_ATENDIMENTO = '5018720'
ORDER BY itsp.CD_PROTOCOLO DESC;

SELECT its.* 
FROM dbamv.IT_SAME its
WHERE its.CD_ATENDIMENTO = '5070001';

SELECT * FROM dbamv.PROTOCOLOS WHERE CD_PROTOCOLO IN (154285, 154262);

SELECT * FROM dbamv.SAME WHERE NR_MATRICULA_SAME = 473152;

SELECT * FROM dbamv.PROTOCOLO;
