SELECT *
FROM V$SQLAREA area
WHERE area.PARSING_SCHEMA_NAME = 'HSSAMPAIO';

SELECT *
FROM ALL_TAB_COLUMNS atc
WHERE atc.COLUMN_NAME LIKE '%DESTINO%'
AND atc.OWNER = 'DBAMV'
ORDER BY 1 ASC;

SELECT * FROM DBAMV.VDIC_RASTREAMENTO_PONTUARIO;

SELECT * FROM dbamv.REG_FAT ORDER BY 1 DESC;
SELECT * FROM Dbamv.PROTOCOLOS ORDER BY 1 DESC;
SELECT * FROM Dbamv.IT_SAME_PROTOCOLOS ORDER BY 1 DESC;
SELECT * FROM DBAMV.SAME ORDER BY 1 DESC;
SELECT * FROM DBAMV.REG_FAT ORDER BY 1 DESC;
SELECT * FROM dbamv.ITREG_FAT ORDER BY 1 DESC;





