---------
--CONTA--
---------

DROP TABLE conta_fat.CONTA;

CREATE TABLE conta_fat.CONTA(
CD_CONTA            INT NOT NULL,
CD_PROTOCOLO        VARCHAR(30) NOT NULL,
TP_STATUS           VARCHAR(1) NOT NULL, -- A - FATURISTA/ATENDENTE | R - RETROCEDE | C - CONCLUIDO
CD_USUARIO_CADASTRO VARCHAR(20) NOT NULL,
HR_CADASTRO         TIMESTAMP(6) NOT NULL,
CD_USUARIO_ULT_ALT  VARCHAR(20),
HR_ULT_ALT          TIMESTAMP(6),

--PRIMARY_KEY
CONSTRAINT PK_CD_CONTA PRIMARY KEY (CD_CONTA)

);

--SEQUENCE  

DROP SEQUENCE conta_fat.SEQ_CONTA;

CREATE SEQUENCE conta_fat.SEQ_CONTA  
START WITH 1    
INCREMENT BY 1
NOCACHE
NOCYCLE;

------------
--MENSAGEM--
------------

DROP TABLE conta_fat.MENSAGEM;

CREATE TABLE conta_fat.MENSAGEM(
CD_MENSAGEM         INT NOT NULL,
CD_CONTA            INT NOT NULL,
TP_MENSAGEM         VARCHAR(1) NOT NULL, -- O - OBSERVACAO
DS_MENSAGEM         CLOB NOT NULL,
CD_USUARIO_CADASTRO VARCHAR(20) NOT NULL,
HR_CADASTRO         TIMESTAMP(6) NOT NULL,
CD_USUARIO_ULT_ALT  VARCHAR(20),
HR_ULT_ALT          TIMESTAMP(6),

--PRIMARY_KEY
CONSTRAINT PK_CD_MENSAGEM PRIMARY KEY (CD_MENSAGEM)

);

--SEQUENCE  

DROP SEQUENCE conta_fat.SEQ_MENSAGEM;

CREATE SEQUENCE conta_fat.SEQ_MENSAGEM  
START WITH 1    
INCREMENT BY 1
NOCACHE
NOCYCLE;

------------
--MENSAGEM--
------------

DROP TABLE conta_fat.MOVIMENTACAO;

CREATE TABLE conta_fat.MOVIMENTACAO(
CD_MOVIMENTACAO     INT NOT NULL,
CD_CONTA            INT NOT NULL,
TP_ORIGEM           VARCHAR(1) NOT NULL, -- F - FATURAMENTO | A - FATURISTA/ATENDENTE
CD_USUARIO_ORIGEM   VARCHAR(20) NOT NULL,
TP_DESTINO          VARCHAR(1) NULL, -- F - FATURAMENTO | A - FATURISTA/ATENDENTE
CD_USUARIO_DESTINO  VARCHAR(20) NULL,
SN_RETROCEDE        VARCHAR(1) NOT NULL, -- S - SIM | N - NAO 
DS_OBSERVACAO       VARCHAR(200) NULL,
CD_USUARIO_CADASTRO VARCHAR(20) NOT NULL,
HR_CADASTRO         TIMESTAMP(6) NOT NULL,
CD_USUARIO_ULT_ALT  VARCHAR(20),
HR_ULT_ALT          TIMESTAMP(6),

--PRIMARY_KEY
CONSTRAINT PK_CD_MOVIMENTACAO PRIMARY KEY (CD_MOVIMENTACAO)

);

--SEQUENCE  

DROP SEQUENCE conta_fat.SEQ_MOVIMENTACAO;

CREATE SEQUENCE conta_fat.SEQ_MOVIMENTACAO  
START WITH 1    
INCREMENT BY 1
NOCACHE
NOCYCLE;

-------------
--FATURISTA--
-------------

DROP TABLE conta_fat.FATURISTA;

CREATE TABLE conta_fat.FATURISTA(
CD_FATURISTA        INT NOT NULL,
CD_USUARIO          VARCHAR(20) NOT NULL,
RGB_FUNDO           VARCHAR(10) NOT NULL,
RGB_FONTE           VARCHAR(10) NOT NULL,
SN_ATIVO            VARCHAR(1) NOT NULL, -- S - SIM | N - NAO 
CD_USUARIO_CADASTRO VARCHAR(20) NOT NULL,
HR_CADASTRO         TIMESTAMP(6) NOT NULL,
CD_USUARIO_ULT_ALT  VARCHAR(20),
HR_ULT_ALT          TIMESTAMP(6),

--PRIMARY_KEY
CONSTRAINT PK_CD_FATURISTA PRIMARY KEY (CD_FATURISTA)

);

--SEQUENCE  

DROP SEQUENCE conta_fat.SEQ_FATURISTA;

CREATE SEQUENCE conta_fat.SEQ_FATURISTA  
START WITH 1    
INCREMENT BY 1
NOCACHE
NOCYCLE;
